### ISSUE TITLE
Add https support

### ISSUE THREAD

**Issue by brint** [edgecase/git_immersion#13]
Any chance of adding HTTPS support to gitimmersion.com? :)

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by nummi** [comment]
Thanks @brint, I'll work on this when I get a chance.

**Comment by corneliusroemer** [comment]
More than a year has passed, not supporting https looks increasingly like "website smell", putting users off even if the content is still totally up to date.

**Comment by tonywok** [comment]
Https is now enforced! Thanks for the issue!
