### ISSUE TITLE
Rename issues link from "Github Issues" to "Report Issue on Github"

### ISSUE THREAD

**Issue by corneliusroemer** [edgecase/git_immersion#15]
Looking through the homepage http://gitimmersion.com/, the link named "Github Issues" sounds to me more like a list of issues that Github has itself, not issues that the immersion website has. Maybe it could be renamed to "Report Issue (on Github)" to make the function of the link clearer.

**Comment by tonywok** [comment]
Good suggestion. I'll try to get to this when I have a moment.
