### ISSUE TITLE
Lab_49 Pulling Shared Changes contains too few explanations

### ISSUE THREAD

**Issue by gitqlt** [edgecase/git_immersion#19]
Executing

    git branch --track shared master
    Branch 'shared' set up to track local branch 'master'.

It seems confusing to me. Being on the `master` branch, do we really need another local branch (tracking the **local** master) for pulling from the `shared` repo? What is this extra branch used for?
I omitted the `git branch...` command and was able to pull the changes out of the `shared` repo.

```
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> sharedrepo/master
Updating 12cb2ff..91a8e6d
Fast-forward
 README | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
````
Thank you

**Comment by tonywok** [comment]
Going through the lab to try and get up to speed 😅 :

1. The lab has us go into the `cloned_hello` repo.
2. We add a remote repository called `shared` pointed at the `hello.git` repo.
3. We set our branch to track the `shared` remote repository's `master` branch.
4. We pull `shared`'s master branch into our local master.

> It seems confusing to me. Being on the master branch, do we really need another local branch (tracking the local master) for pulling from the shared repo? What is this extra branch used for?

I think this is simulating a scenario in which you have a git repository that tracks the master branch of two separate remote repositories.

Let me know if I'm misunderstanding -- perhaps there's some more copy we can add to further explain.
