### ISSUE TITLE
First few steps fail to walkthrough how to create the hello.rb

### ISSUE THREAD

**Issue by dbooyah93** [edgecase/git_immersion#25]
Lab 3 Is formatted differently online and in the downloadable folders. In the folders there is FILE: hello.rb which tipped me off that maybe i need to use > hello.rb to create the file. However, the puts "Hello World" is not putting that text into the hello.rb file, which i expected the walk through to show me how to do these things. I'm using windows 10 with git bash and ubuntu so maybe that's my problem.

**Comment by tonywok** [comment]
@dbooyah93 Did you figure it out?

**Comment by dbooyah93** [comment]
It was wildly difficult, but I'm using git now to commit, track history, create branches, clone, and push.

**Comment by tonywok** [comment]
@dbooyah93 Glad you got past it! But just to make sure I understand the confusion (in case there should be an improvement!)

I just took a look at lab 3. It says:

> Starting in the empty working directory, create an empty directory named “hello”, then create a file named `hello.rb` with the contents below.

Based on how you interpreted it, were you expecting to type `puts "Hello, World"` in the shell and have it populate the `hello.rb` file for you?

And are you saying you got around this by changing it to: `'puts "Hello, World"' > hello.rb`?

**Comment by dbooyah93** [comment]
I did this:
> hello.rb
then
nano hello.rb
then inside that I typed 
puts "Hello World"


the only reason i tried these steps is because a youtube video showed me those steps. I also didn't know how to save with esc and :wq, but my class showed me that and I should have known sooner.

**Comment by tonywok** [comment]
Gotcha, thanks for following up. Is there anything you'd like to see added to help clarify for others? 😎 

Text editing gets pretty cryptic quickly -- good on you for figuring it out. Definitely don't feel like you "should have known", but your determination will continue to serve you!
