### ISSUE TITLE
Lab 15 - bring up to date with current suggestion text

### ISSUE THREAD

**Issue by JeffHoover** [edgecase/git_immersion#32]
In Lab 15, current git no longer suggests "git reset head". See below for current behavior:
```
% git status
On branch main
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   hello.rb
```

**Comment by JeffHoover** [comment]
Likely applies to some other labs that use "git status", including #20

**Comment by tonywok** [comment]
Good call out, Jeff. Sorry a bit late getting to this. Inbox a bit flooded.
