### ISSUE TITLE
Broken Tutorial Package Link

### ISSUE THREAD

**Issue by jaredDlewis** [edgecase/git_immersion#33]
On the "[More Setup](https://gitimmersion.com/lab_02.html)" Page, the existing Tutorial Package link is http://gitimmersion.com/git_tutorial.zip which does not work, but changing it to "https" works -> https://gitimmersion.com/git_tutorial.zip

**Comment by jslpc** [comment]
To piggy back off of this, the Ruby installation link on [Lab 1](https://gitimmersion.com/lab_01.html) is broken as well.

Current: https://www.ruby-lang.org/en/installation/  
Fixed: https://www.ruby-lang.org/en/downloads/

**Comment by tonywok** [comment]
Thanks! I get this sorted this week.

**Comment by tonywok** [comment]
Should be taken care of. Thanks for raising the issue 🥇
