### ISSUE TITLE
Revise Tutorial 'Contact Us' Link

### ISSUE THREAD

**Issue by idfubar** [edgecase/git_immersion#7]
The 'Get in contact with Neo' link could be made functional, e.g. made a 'mailto:' link with a default addressing (a mailing list for 'edgecase/git_immersion' repository contributors, say...); good/not good...?

**Comment by idfubar** [comment]
@mdoel @tonywok @switchhax - any thoughts/ideas...?

**Comment by nummi** [comment]
Removed Neo link in new design. Thanks!
