### ISSUE TITLE
Lab 30 - Traduction error in the "execute" section

### ISSUE THREAD

**Issue by n3wborn** [edgecase/git_immersion#8]
The branch name in [http://gitimmersion.fr/lab_30.html#main_content](Lab 30) is the english one.
According to the previous names provided for each branch, the branch in this exercise should be named "saluer". So, the Execute Section should be like this :

Execute:

- $ git checkout saluer

- $ git merge master

The same translation error appears in the Output Section.

**Comment by tonywok** [comment]
Going to close for now since it's been awhile and I don't think that version is affiliated with this repository -- though it would be cool to get this translated!

Please feel free to re-open if you have more information about gitimmersion.fr (first I'm hearing about it).
